### PR TITLE
Bottom toolbar

### PR DESCRIPTION
**Pull request by DurkoMatko**
add: bottom toolbar component with its private routes
add: SASS support

### CODE REVIEW

**Comment by DurkoMatko** [comment]
[Create Front End Tab Bar link it with the 'Scan QR Code' Component #small #react](https://trello.com/c/eYGAyMSA/536-create-front-end-tab-bar-link-it-with-the-scan-qr-code-component-small-react)

**Comment by aerinsol** [comment]
@soheimam @DurkoMatko if we are going to be using Semantic, should this pull in the Semantic style instead?

**Comment by DurkoMatko** [comment]
@aerinsol hm I've thought there's no bottom bar in semantic (just tabs and sidebar)..but double-checking now, it seems one can use side-bar as bottom bar. I can give it a try.

**Review by mcgnly — APPROVED** [review]
works for me

**Pull request merged**
