### PR TITLE
Header bar

### PR DESCRIPTION
**Pull request by DurkoMatko**
**add**: header bar with all bases for the organisation 
- currently just querying with orgId=2
- semantic-ui dropdown will be replaced with our dropdown once our UI lib is ready

**fix**: linting errors (I feel we should be respecting current config even if we plan on adjusting them in the future)

### CODE REVIEW

**Comment by DurkoMatko** [comment]
[Create FE header bar and link it with PHP app #small #react](https://trello.com/c/zbEEmGVo/537-create-fe-header-bar-and-link-it-with-php-app-small-react)

**Comment by cohenlea** [comment]
@aerinsol @DurkoMatko with the mobile to desktop redirects, it should stay in the same environment, correct? When I click the desktop icon it leaves local and takes me to https://app.boxwise.co/

**Comment by cohenlea** [comment]
@DurkoMatko I tried logging in with two different users and I get "error fetching bases" in the dropdown. Which users can I try?
But otherwise I really like the layout/design of the header bar! nice work :)

**Comment by mcgnly** [comment]
Screenshot 2020-08-07 at 21 18 52
I'm also getting the error in the dropdown- otherwise it looks great to me!

**Comment by mcgnly** [comment]
this seems like A Clue:
Screenshot 2020-08-07 at 21 46 39

**Comment by DurkoMatko** [comment]
@cohenlea @mcgnly thx for the review! With what user are you guys getting the error? I'm not able to reproduce the issue. Tried with my gmail account as well as with these users: 
image

**Comment by mcgnly** [comment]
I think it's not user-specific, because Lea and I got it with different test users. Could it be that you don't have the most current version of the backend/db?

**Comment by DurkoMatko** [comment]
@mcgnly I've recreated the mysql container yesterday morning...do you get some data back with this query in the Playground?
```
query orgBases($org_id: Int = 2) {
  orgBases(org_id: $org_id) {
    id
    organisation_id
    name
  }
}
```

**Comment by DurkoMatko** [comment]
In the meantime the feature got implemented in https://github.com/boxwise/boxwise-react/pull/21 with the new styling (without graphql part).  GraphQL query will need to be added to the other version, otherwise this is obsolete now. Closing this PR.

**Pull request closed without merging**
